services:
#    test.example:
#        class: TestBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  pdo_flysystem_service:
    class: TestBundle\Service\PdoFlySystem
    arguments: ['@doctrine.orm.entity_manager']
